# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prtr < Formula
  desc "Think in your language and send the right prompt to the right AI app."
  homepage "https://github.com/helloprtr/poly-prompt"
  version "0.3.5"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/helloprtr/poly-prompt/releases/download/v0.3.5/prtr_0.3.5_darwin_amd64.tar.gz"
      sha256 "d68c5783718eb40e116669906c146a30289f75a873d0c4f0ef01544848bc0c53"

      define_method(:install) do
        bin.install "prtr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/helloprtr/poly-prompt/releases/download/v0.3.5/prtr_0.3.5_darwin_arm64.tar.gz"
      sha256 "3268e635d87c8bd5cc9a8bed90a8730ebed15973f9b8d1fd17ddb8c26919e668"

      define_method(:install) do
        bin.install "prtr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/helloprtr/poly-prompt/releases/download/v0.3.5/prtr_0.3.5_linux_amd64.tar.gz"
      sha256 "d19b79dde862552278d725412cf311ac4b9eca8aca1c3d38a8997d8c575f6da8"
      define_method(:install) do
        bin.install "prtr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/helloprtr/poly-prompt/releases/download/v0.3.5/prtr_0.3.5_linux_arm64.tar.gz"
      sha256 "27921bdcf8c8c28bba52046de5fadd64b7d7fd2bbf9a8fa3252bc78c0971e4a9"
      define_method(:install) do
        bin.install "prtr"
      end
    end
  end

  test do
    system "#{bin}/prtr", "version"
  end
end
