# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Prtr < Formula
  desc "Think in your language and send the right prompt to the right AI app."
  homepage "https://github.com/helloprtr/poly-prompt"
  version "0.6.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/helloprtr/poly-prompt/releases/download/v0.6.3/prtr_0.6.3_darwin_amd64.tar.gz"
      sha256 "805620ebcfc9840d4b8a524d76be6cae795727e7713cd70ef6be3da34e400167"

      define_method(:install) do
        bin.install "prtr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/helloprtr/poly-prompt/releases/download/v0.6.3/prtr_0.6.3_darwin_arm64.tar.gz"
      sha256 "02432da3e3939035109e4c9130d39870f5937aedc88ef17e600b41ae95442cbe"

      define_method(:install) do
        bin.install "prtr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/helloprtr/poly-prompt/releases/download/v0.6.3/prtr_0.6.3_linux_amd64.tar.gz"
      sha256 "6b74b16ecf99be4a7567747a8e19a3911a35be9d003764c3a0d3305770cbce52"
      define_method(:install) do
        bin.install "prtr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/helloprtr/poly-prompt/releases/download/v0.6.3/prtr_0.6.3_linux_arm64.tar.gz"
      sha256 "c5cf28fe6a8b3dca4f8ad7c446f4ff8a4943351ae12a6cbb3a9378049634b6af"
      define_method(:install) do
        bin.install "prtr"
      end
    end
  end

  test do
    system "#{bin}/prtr", "version"
  end
end
